#!/usr/bin/env python3
"""
Demo script for Human Behavior Detection System
==============================================

This script demonstrates the key features of the system:
1. Interactive menu system
2. Saved video analysis
3. Real-time camera analysis
4. Chatbot integration
"""

import sys
import os
from pathlib import Path

# Add current directory to path for imports
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

def demo_interactive_menu():
    """Demonstrate the interactive menu system."""
    print("🎯 DEMO: Interactive Menu System")
    print("=" * 50)
    print("The system provides an interactive menu with the following options:")
    print()
    print("1. 📹 Analyze Saved Videos")
    print("   - Select from videos in data/raw_videos/")
    print("   - Choose individual video or analyze all")
    print("   - View detailed behavior analysis results")
    print()
    print("2. 🎥 Real-time Camera Analysis")
    print("   - Use your webcam for live behavior detection")
    print("   - Press 'q' to quit, 'c' to chat")
    print("   - See pose landmarks overlaid on video")
    print()
    print("3. 🔄 Run Full Pipeline")
    print("   - Complete workflow: frames → pose → behavior → alerts")
    print("   - Configurable frame extraction rate")
    print()
    print("4. 💬 Chat with AI Assistant")
    print("   - Ask questions about detected behaviors")
    print("   - Get statistics and summaries")
    print("   - Query alert history")
    print()
    print("5. 📊 System Status")
    print("   - Check system health and data availability")
    print()
    print("6. 🧪 Test System")
    print("   - Run comprehensive system tests")
    print()
    print("0. 🚪 Exit")
    print()
    print("To start the interactive menu, run:")
    print("   python main.py --mode interactive")
    print()

def demo_saved_video_analysis():
    """Demonstrate saved video analysis."""
    print("📹 DEMO: Saved Video Analysis")
    print("=" * 50)
    print("This feature analyzes pre-recorded video files:")
    print()
    print("1. Place MP4 videos in data/raw_videos/")
    print("2. Select option 1 from the main menu")
    print("3. Choose a video or analyze all")
    print("4. View results showing:")
    print("   - Detected behaviors and percentages")
    print("   - Confidence scores")
    print("   - Triggered alerts")
    print()
    print("Example output:")
    print("📊 ANALYSIS RESULTS: assault_violence (1).mp4")
    print("=" * 50)
    print("📹 Video: assault_violence (1).mp4")
    print("📊 Total frames: 150")
    print("🎯 High confidence frames: 142")
    print("📈 Confidence rate: 94.7%")
    print()
    print("🎭 Detected Behaviors:")
    print("   • fighting: 45 frames (30.0%)")
    print("   • normal: 105 frames (70.0%)")
    print()
    print("🚨 Alerts Triggered: 1")
    print("   • fighting - critical severity")
    print("=" * 50)
    print()

def demo_realtime_analysis():
    """Demonstrate real-time analysis."""
    print("🎥 DEMO: Real-time Camera Analysis")
    print("=" * 50)
    print("This feature provides live behavior detection:")
    print()
    print("1. Select option 2 from the main menu")
    print("2. Choose your camera (usually 0 for default)")
    print("3. The system will:")
    print("   - Open your webcam")
    print("   - Detect poses in real-time")
    print("   - Classify behaviors every 2 seconds")
    print("   - Display results in terminal")
    print("   - Show pose landmarks on video")
    print()
    print("Controls:")
    print("   - Press 'q' to quit")
    print("   - Press 'c' to open chatbot")
    print()
    print("Example terminal output:")
    print("[14:32:15] Behavior: normal (Confidence: 0.87)")
    print("[14:32:17] Behavior: falling (Confidence: 0.92)")
    print("[14:32:17] 🚨 ALERT: falling detected!")
    print("[14:32:19] Behavior: normal (Confidence: 0.89)")
    print()
    print("The video window shows:")
    print("   - Live camera feed")
    print("   - Green circles on detected body landmarks")
    print("   - Landmark names (nose, shoulders, etc.)")
    print()

def demo_chatbot():
    """Demonstrate chatbot functionality."""
    print("💬 DEMO: AI Chatbot Assistant")
    print("=" * 50)
    print("The chatbot can answer questions about:")
    print()
    print("📊 Analysis Results:")
    print("   - 'What behaviors were detected?'")
    print("   - 'Show me statistics about falling behavior'")
    print("   - 'How many videos have been processed?'")
    print()
    print("🚨 Alert Information:")
    print("   - 'Show me recent alerts'")
    print("   - 'What alerts were triggered?'")
    print("   - 'Show critical alerts'")
    print()
    print("📹 Video Information:")
    print("   - 'What happened in video X?'")
    print("   - 'List all processed videos'")
    print("   - 'Show video analysis summary'")
    print()
    print("Example conversation:")
    print("You: What behaviors were detected?")
    print("🤖 Here's a summary of detected behaviors:")
    print("   • Normal: 70% of frames")
    print("   • Fighting: 20% of frames")
    print("   • Falling: 10% of frames")
    print()
    print("You: Show me recent alerts")
    print("🤖 Recent alerts:")
    print("   • 14:30:15 - Fighting detected (Critical)")
    print("   • 14:28:42 - Falling detected (High)")
    print()
    print("You: How many videos were processed?")
    print("🤖 30 videos have been processed with an average")
    print("   pose detection rate of 85%.")
    print()

def demo_usage_examples():
    """Show usage examples."""
    print("🚀 USAGE EXAMPLES")
    print("=" * 50)
    print()
    print("1. Quick Start (Interactive Mode):")
    print("   python main.py --mode interactive")
    print()
    print("2. Analyze Specific Video:")
    print("   python main.py --mode extract_frames --fps 2")
    print("   python main.py --mode extract_pose")
    print("   python main.py --mode analyze")
    print()
    print("3. Run Complete Pipeline:")
    print("   python main.py --mode full_pipeline --fps 1")
    print()
    print("4. Start Chatbot Only:")
    print("   python main.py --mode chat")
    print()
    print("5. Check System Status:")
    print("   python main.py --status")
    print()
    print("6. Test System Components:")
    print("   python test_system.py")
    print()

def main():
    """Run the demo."""
    print("🤖 HUMAN BEHAVIOR DETECTION SYSTEM - DEMO")
    print("=" * 60)
    print()
    
    demo_interactive_menu()
    demo_saved_video_analysis()
    demo_realtime_analysis()
    demo_chatbot()
    demo_usage_examples()
    
    print("🎯 NEXT STEPS")
    print("=" * 50)
    print("1. Install dependencies: pip install -r requirements.txt")
    print("2. Add videos to data/raw_videos/")
    print("3. Start the system: python main.py --mode interactive")
    print("4. Explore the features!")
    print()
    print("📚 For more information, see README.md")
    print("🆘 For help, run: python test_system.py")

if __name__ == "__main__":
    main() 